/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudMotionSensor motion;
  CloudTemperatureSensor temperature;
  int moisture;
  int sound;
  CloudRelativeHumidity humidity;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/


//Humidity sensor
#include "thingProperties.h"
#include <DHT.h>
#define DHT11_PIN 5
#define DHTTYPE DHT11
DHT dht(DHT11_PIN, DHTTYPE);

//Sound sensor
const int sound_sensor = 14;

//PIR Sensor
int PIR_sensor = 12;

//Moisture Sensor
int Moisture_sensor = 13;

/////////////////

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
  */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  //Temperature and Humidity
  ArduinoCloud.update();
  float hm = dht.readHumidity();
  Serial.print('Humidity-'); Serial.println(hm);
  float temp = dht.readTemperature();
  Serial.print('Temperature-'); Serial.println(temp);
  humidity = hm;
  temperature = temp;
  {
    //Sound_sensor
    ArduinoCloud.update();
    sound = analogRead(sound_sensor);
  }
  {
    //PIR sensor
    ArduinoCloud.update();
    motion = analogRead(PIR_sensor);
  }
  {
    //Moisture Sensor
    ArduinoCloud.update();
    moisture = analogRead(Moisture_sensor);
  }
}
